
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_econ'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_econ'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_econ:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
vars:
  fred_indicators:
    - {name: 'unemployment_rate', table_name: 'unemployment_rate', series_id: 'UNRATE'}
    - {name: 'cpi', table_name: 'consumer_price_index', series_id: 'CPIAUCSL'}
    - {name: 'core_cpi', table_name: 'core_consumer_price_index', series_id: 'CPILFESL'}
    - {name: 'pce', table_name: 'personal_consumption_expenditures_index', series_id: 'PCEPI'}
    - {name: 'real_gdp', table_name: 'real_gdp', series_id: 'GDPC1'}
    - {name: 'real_gdp_per_capita', table_name: 'real_gdp_per_capita', series_id: 'A939RX0Q048SBEA'}
    - {name: 'real_income_per_capita', table_name: 'real_income_per_capita', series_id: 'RPI'}
    - {name: 'real_median_household_income', table_name: 'real_median_household_income', series_id: 'MEHOINUSA672N'}
