import json
import os
import yaml

# This file auto-generates a sources.yml file for my associated DBT project. 
# fred_series.json contains the appropriate file configuration.
# The function defined here will keep my dbt project up to date automatically.
# I want to note that at the time I created this, I'm only dealing with date indexed FRED data.
# Working with a differnet index may necessiate new files

def generate_sources_file():
    # Gemini did most of the formatting below.
    # 1. Load your master config file
    config_path = 'config/fred_series.json'
    with open(config_path, 'r') as f:
        indicators = json.load(f)

    # 2. Build the dictionary structure for the YAML
    # dbt sources require a specific hierarchy: version -> sources -> tables
    sources_dict = {
        "version": 2,
        "sources": [
            {
                "name": "fred_raw",
                "description": "Raw economic data ingested from the FRED API.",
                "schema": "raw",
                "schema": "raw",     # The schema where your Python script dumps data
                "tables": [
                    {
                        "name": ind['table_name'],
                        "description": f"Raw data for {ind['name']} (Series ID: {ind['series_id']})"
                    }
                    for ind in indicators
                ]
            }
        ]
    }

    # 3. Define the output path
    # This should point to your dbt staging folder
    output_path = 'dbt_econ/models/staging/sources.yml'
    
    # Create directory if it doesn't exist
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # 4. Write the file
    with open(output_path, 'w') as f:
        # We add a warning header so you don't accidentally edit the YAML by hand
        f.write("# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.\n")
        f.write("# To update, change config/fred_series.json and run this script.\n\n")
        
        # yaml.dump converts the Python dictionary into a YAML-formatted string
        yaml.dump(
            sources_dict, 
            f, 
            sort_keys=False,         # Keeps our 'version' at the top
            default_flow_style=False # Ensures nice, readable block formatting
        )

    print(f"✅ Successfully generated {output_path} with {len(indicators)} tables.")

if __name__ == "__main__":
    print(generate_sources_file())
