import json
import os
import yaml

# This script generates a project.yml file with an updated source variable.
# Updating project.yml will update the variables as I add in more FRED series.

def create_dbt_project_yml():
    config_path = 'config/fred_series.json'
    with open(config_path, 'r') as f:
        indicators = json.load(f)
    

    sources_dict = {
    "name": "dbt_econ",
    "version": "1.0.0",
    "profile": "dbt_econ",
    "model-paths": ["models"],
    "analysis-paths": ["analyses"],
    "test-paths": ["tests"],
    "seed-paths": ["seeds"],
    "macro-paths": ["macros"],
    "snapshot-paths": ["snapshots"],
    "clean-targets": ["target", "dbt_packages"],
    "models": {
        "dbt_econ": {
            "example": {
                "+materialized": "view"
            }
        }
    },
    "vars": {
        "fred_indicators": [
                {"name": ind['name'], "table_name": ind['table_name'], "series_id": ind["series_id"]}
                for ind in indicators
            ]
        }
    }

    output_path = "dbt_econ/dbt_project.yml"

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Wite file.
    with open(output_path, "w") as f:
        # We add a warning header so you don't accidentally edit the YAML by hand
        f.write("# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.\n")
        f.write("# To update, change config/fred_series.json and run this script.\n\n")
        
        # yaml.dump converts the Python dictionary into a YAML-formatted string
        yaml.dump(
            sources_dict, 
            f, 
            sort_keys=False,         # Keeps our 'version' at the top
            default_flow_style=False # Ensures nice, readable block formatting
        )

    print(f"✅ Successfully generated {output_path} with {len(indicators)} tables.")


create_dbt_project_yml()